### ISSUE TITLE
[FEAT] Firebase 기반으로 두 유저를 매칭하고, 기존 뷰모델에 ObservableObject 속성을 추가합니다.

### ISSUE THREAD

**Issue by RubiksCube33** [GYURI-PARK/MC2_Morning_0404#13]
MatchingLoadingView에 사용된 뷰모델인
MatchingLoadingViewModel을 다듬을 예정입니다.

추가적으로 뷰모델에 ObservableObject 속성을 부여해서
View 내에서 StateObject로 사용이 가능하게 만듭니다.

목표 소요 시간 : 3시간

**Comment by dayo2n** [comment]
매칭이 AuthViewModel 내에 기능이 다 들어가있어서 
제 생각에는 1. 새로운 기능 필요없이 뷰모델을 분리하거나 
2. AuthViewModel은 싱글톤 패턴으로 어디서든 쓸 수 있어서 필요없을 것 같은데 어떻게 생각하시나여

**Comment by RubiksCube33** [comment]
> 
저도 비슷하게 생각합니다.
지금 팀원들 다 불러서 말하기가 힘들어서 일단 어떻게든 설계 파일대로 하려고 한 것인데,
AuthViewModel로 커버가 다 되다 보니까 이게 굳이 필요한가? 싶더라고요...

**Comment by dayo2n** [comment]
> > 
> 
> 저도 비슷하게 생각합니다. 지금 팀원들 다 불러서 말하기가 힘들어서 일단 어떻게든 설계 파일대로 하려고 한 것인데, AuthViewModel로 커버가 다 되다 보니까 이게 굳이 필요한가? 싶더라고요...

제 생각에는 제 지난 코멘트의 2번으로 가다가 이후에 필요하다면 추가로 진행하면 될 것 같은데 괜찮으신가요?
괜찮으시면 #12 에 오늘 추가해주신 마지막 커밋 내용은 삭제하고 머지할까 합니다 ~~
걸리는 부분 있으시면 언급해 주세요!
