### ISSUE TITLE
[FEAT] 뒤로가기 / 앞으로가기 기능 구현

### ISSUE THREAD

**Issue by GYURI-PARK** [GYURI-PARK/MC2_Morning_0404#16]
목표 : 기숙사 도착 ~ 잠들기 전까지💤

<img width="265" alt="KakaoTalk_Photo_2023-05-07-14-56-33" src="https://user-images.githubusercontent.com/93391058/236660434-6ab02536-20d2-47cb-a781-faf2662cef1f.png">

저기 저 버튼 두개 기능 구현하기

**Comment by dayo2n** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ잠들기 전까지💤
도리스 홧팅 🍀💪🤓
