### ISSUE TITLE
[FEAT] Firebase에 익명으로 로그인을 하고, 매칭코드를 제작합니다.

### ISSUE THREAD

**Issue by RubiksCube33** [GYURI-PARK/MC2_Morning_0404#3]
![스크린샷 2023-05-05 오후 3 48 49](https://user-images.githubusercontent.com/67681580/236393317-b1c66548-4bae-4fc0-bb83-2850ccd28923.png)

Firebase에 익명으로 로그인을 진행하고,
로그인 정보를 바탕으로 매칭코드를 제작합니다.

예상 마감 시간 : 3시간 (목표)

**Comment by dayo2n** [comment]
매칭코드 == 익명 사용자 UID 이용하는걸로 그대로 가는거 맞을까요 ?

**Comment by RubiksCube33** [comment]
> 

넵 그렇게 가는 방향으로 하고 있습니다!
