### ISSUE TITLE
[REFACTOR] 일관성 있는 코드 작성을 위해 User 모델을 수정합니다.

### ISSUE THREAD

**Issue by RubiksCube33** [GYURI-PARK/MC2_Morning_0404#7]
![스크린샷 2023-05-05 오후 7 28 04](https://user-images.githubusercontent.com/67681580/236434870-814f87a1-3d95-4173-9ba3-b3284ea33146.png)

현재 User 모델 구조체 내부에는 옵셔널로 선언된 변수와
옵셔널이 아닌 변수가 혼재되어 있습니다.

그런데 코드를 작성하다 보니, User 모델이 초기화될 때
모든 변수를 UserDefaults에서 옵셔널로 받아와야
우리가 의도한 대로 기능 구현이 가능했습니다.

따라서 모든 변수를 옵셔널로 선언하고 UserDefaults에서 불러온 정보를 바로 넣어서
변수를 호출할 때마다 옵셔널 바인딩을 하거나,
아니면 변수에 데이터를 넣는 순간에 UserDefaults에서 받아온 데이터를 옵셔널 바인딩으로 넣고
데이터가 없으면 "NO_DATA", false 등의 정해진 초기값을 변수에 할당한 뒤
이후에는 그냥 사용하는 방법이 있는데...

지금 모델에서는 어떤 변수는 옵셔널이고, 나머지는 아닌 상황이라서
코드를 짜다 보니 어떻게든 작동시킬 수가 있긴 한데, 변수에 따라 호출 방식이 오락가락하는
복잡하고 헷갈리기 좋은 코드가 작성되더라고요.

따라서 일관성 있는 변수 사용을 위해 모델 데이터를 모두 비 옵셔널로 바꾸고
UserDefaults를 사용해 저장된 데이터를 받아올 때 (초기화 단계에서)
옵셔널 바인딩을 하는 방식을 사용하는 것을 제안하고자 합니다.

예상 작업 시간 : 10분

**Comment by dayo2n** [comment]
```
모든 변수를 UserDefaults에서 옵셔널로 받아와야
우리가 의도한 대로 기능 구현이 가능했습니다.
```
이 부분이 왜인지 설명해주실 수 있을까요?

**Comment by RubiksCube33** [comment]
> 

로컬에 저장 가능한 데이터는 최대한 로컬에 저장해서 호출하는 형태로 구현을 했는데,
이 과정에서 특정 변수에 대입할 로컬 데이터를 불러올 때 전부 옵셔널 형태로 데이터를 받아야 했습니다.

그런데 User 내에 있는 변수들이 어떤건 옵셔널이고 어떤건 아니다 보니
변수에 따라 호출방법이 달라서 코드가 엉망이 되더라고요.
그래서 전부 옵셔널로 받거나, 아니면 전부 일반 변수로 해놓고 초기화를 할때 옵셔널 값 받아오는걸 체크해서
받아와야 코드가 깔끔하게 나왔습니다.

**Comment by dayo2n** [comment]
코드를 봐야 알겠지만, 옵셔널을 확인하는 코드가 있는 게 꼭 나쁘고 지저분한 코드는 아니라고 생각해요.

옵셔널 자체의 역할이 무엇인지를 생각해 보면 될 것 같아요.
옵셔널이 무엇인가요? 기본적인 뜻은 값이 있을 수도, 없을 수도 있다는 뜻이지요
우리 앱에서 유저가 가지는 partnerID, imageUrl도 같아요. 연결이 없는 상태에선 없는 값이니까요

옵셔널이 nil인지 아닌지 확인하는 코드와 무조건 값을 넣되 dummy값인지 아닌지를 확인하는 코드가 루빅이 보기에 깔끔하다는 부분에서 얼마나 차이가 나던가요?
코드를 깔끔하게 짜는 것이 정확하고 옳은 코드일지 고려할 필요가 있어 보입니다

---
그리고 지금 보니 partnerID와 imageURL은 카멜케이스에 어긋나고 있네요! 
문서 작성할 때 저렇게 작성된 거죠? 가능하다면 같이 수정 부탁드려요 :)

**Comment by RubiksCube33** [comment]
> 코드를 봐야 알겠지만, 옵셔널을 확인하는 코드가 있는 게 꼭 나쁘고 지저분한 코드는 아니라고 생각해요.
> 
> 옵셔널 자체의 역할이 무엇인지를 생각해 보면 될 것 같아요. 옵셔널이 무엇인가요? 기본적인 뜻은 값이 있을 수도, 없을 수도 있다는 뜻이지요 우리 앱에서 유저가 가지는 partnerID, imageUrl도 같아요. 연결이 없는 상태에선 없는 값이니까요
> 
> 옵셔널이 nil인지 아닌지 확인하는 코드와 무조건 값을 넣되 dummy값인지 아닌지를 확인하는 코드가 루빅이 보기에 깔끔하다는 부분에서 얼마나 차이가 나던가요? 코드를 깔끔하게 짜는 것이 정확하고 옳은 코드일지 고려할 필요가 있어 보입니다
> 
> 그리고 지금 보니 partnerID와 imageURL은 카멜케이스에 어긋나고 있네요! 문서 작성할 때 저렇게 작성된 거죠? 가능하다면 같이 수정 부탁드려요 :)

맞아요 그렇긴 한데... 문제가 저희가 처음에 코드를 설계할 때 일부 값은 옵셔널, 일부 값은 그냥 값으로 했다는 건데
지금 설계를 하다 보니 앱을 최초로 실행하면 userID 같은 것도 옵셔널로 받아와야 하는 상황이라서
이왕 하는 거라면 전부 다 통일해서 처리를 해야 코드가 깔끔해질 것 같았습니다.

**Comment by dayo2n** [comment]
이슈 해결되었으니 닫겠습니다 !
